require "configs.catppuccin-config"
require "configs.telescope-config"
require "configs.rose-pine-config"
require	"configs.tokyonight-config"
require	"configs.treesitter-config"
require	"configs.nvimtree-config"
require "configs.lualine-config"
require "configs.alpha-config"
require "configs.undo-config"
require "configs.lsp-config"
require "configs.cmp-config"
require "configs.mason-config"
require "configs.gitsigns-config"
require "configs.github-theme-config"

require "configs.toggleterm-config"
