-- Generated by nwg-displays on 2026-08-12 at 12:19:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.0",
    position = "2560x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@180.0",
    position = "0x0",
    scale = 1.0
})
