-- Generated by nwg-displays on 2026-07-11 at 17:57:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 1.0
})
