-- Generated by nwg-displays on 2026-08-18 at 20:53:33. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "0x0",
    scale = 0.9999999999999997
})
